staging:
  sessions:
    default:
      database: cbecc_com_web_staging
      hosts:
        - 127.0.0.1:27017
      options:
vagrant:
  sessions:
    default:
      database: cbecc_com_web_vagrant
      hosts:
        - 127.0.0.1:27017
      options:
production:
  sessions:
    default:
      database: cbecc_com_web_prod
      hosts:
        - 127.0.0.1:27017
      options:
development:
  sessions:
    default:
      database: cbecc_com_web_dev
      hosts:
        - 127.0.0.1:27017
      options:
test:
  sessions:
    default:
      database: cbecc_com_web_test
      hosts:
        - 127.0.0.1:27017
      options:
        read: primary
        max_retries: 1
        retry_interval: 0
