class HeatRejection
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String
  field :status, type: String
  field :type, type: String
  field :fan_type, type: String
  field :modulation_control, type: String
  field :fluid_segment_in_reference, type: String
  field :fluid_segment_out_reference, type: String
  field :entering_temperature_design, type: Float
  field :design_wb_temperature, type: Float
  field :leaving_temperature_design, type: Float
  field :cell_count, type: Float
  field :capacity_rated, type: Float
  field :total_fan_hp, type: Float
  field :air_flow_capacity, type: Float
  field :water_flow_capacity, type: Float
  field :power_f_plr_curve_reference, type: String
  field :low_speed_air_flow_ratio, type: Float
  field :low_speed_power_ratio, type: Float
  field :minimum_speed_ratio, type: Float

  belongs_to :fluid_system
  has_many :pumps, dependent: :destroy


  def self.children_models
    children = [
       { model_name: 'pump', xml_name: 'Pump' }
    ]
  end

  def self.xml_fields
    xml_fields = [
      {:db_field_name=>"name", :xml_field_name=>"Name"},
      {:db_field_name=>"status", :xml_field_name=>"Status"},
      {:db_field_name=>"type", :xml_field_name=>"Type"},
      {:db_field_name=>"fan_type", :xml_field_name=>"FanType"},
      {:db_field_name=>"modulation_control", :xml_field_name=>"ModCtrl"},
      {:db_field_name=>"fluid_segment_in_reference", :xml_field_name=>"FluidSegInRef"},
      {:db_field_name=>"fluid_segment_out_reference", :xml_field_name=>"FluidSegOutRef"},
      {:db_field_name=>"entering_temperature_design", :xml_field_name=>"EntTempDsgn"},
      {:db_field_name=>"design_wb_temperature", :xml_field_name=>"DsgnWBTemp"},
      {:db_field_name=>"leaving_temperature_design", :xml_field_name=>"LvgTempDsgn"},
      {:db_field_name=>"cell_count", :xml_field_name=>"CellCnt"},
      {:db_field_name=>"capacity_rated", :xml_field_name=>"CapRtd"},
      {:db_field_name=>"total_fan_hp", :xml_field_name=>"TotFanHP"},
      {:db_field_name=>"air_flow_capacity", :xml_field_name=>"AirFlowCap"},
      {:db_field_name=>"water_flow_capacity", :xml_field_name=>"WtrFlowCap"},
      {:db_field_name=>"power_f_plr_curve_reference", :xml_field_name=>"Pwr_fPLRCrvRef"},
      {:db_field_name=>"low_speed_air_flow_ratio", :xml_field_name=>"LowSpdAirFlowRat"},
      {:db_field_name=>"low_speed_power_ratio", :xml_field_name=>"LowSpdPwrRat"},
      {:db_field_name=>"minimum_speed_ratio", :xml_field_name=>"MinSpdRat"}
    ]
  end


  # This method is autogenerated. Do not change directly.
  def to_sdd_xml(parent, xml)
    xml.send(parent[:xml_name]) do
      self.class.xml_fields.each do |field|
        xml.send(:"#{field[:xml_field_name]}", self[field[:db_field_name]]) if self[field[:db_field_name]]
      end
      # go through children if they have something to add, call their methods
      kids = self.class.children_models
      unless kids.nil? || kids.empty?
        kids.each do |k|
          models = self.send(k[:model_name].pluralize)
          models.each do |m|
            m.to_sdd_xml(k, xml)
          end
        end
      end
    end
  end
      
  # This method is autogenerated. Do not change directly.
  # Take the map of model name and xml name, and the hash (from the XML).
  def self.from_sdd_json(parent, h)
    o = nil
    if parent && h
      self_model = parent[:model_name].camelcase(:upper).constantize
      o = self_model.create_from_sdd_json(parent, h)
      if o
        o.create_children_from_sdd_json(parent, h)
        o.save!
        o.reload # in case of relationships being updated
      end
    end

    o
  end
  
  # This method is autogenerated. Do not change directly.
  def self.create_from_sdd_json(parent, h)
    new_h = {}

    # Find fields as defined by the XML
    self_model = parent[:model_name].camelcase(:upper).constantize
    self_model.xml_fields.each do |field|
      if h[field[:xml_field_name]]
        logger.debug "Field Data Type: #{self_model.fields[field[:db_field_name]].options[:type]}"
        if self_model.fields[field[:db_field_name]].options[:type].to_s == 'Array'
          logger.debug "Data model has an array as the field"
          # check if the hash has an array, otherwise make it an array
          if h[field[:xml_field_name]].is_a? Array
            logger.debug "XML/JSON field is already an Array"
            new_h[field[:db_field_name]] = h[field[:xml_field_name]]
          else
            new_h[field[:db_field_name]] = [h[field[:xml_field_name]]]
          end
        else
          new_h[field[:db_field_name]] = h[field[:xml_field_name]]
        end

      end
    end

    o = self_model.new(new_h) unless new_h.empty?

    o
  end

  # This method is autogenerated. Do not change directly.
  def create_children_from_sdd_json(parent, h)
    # Go through the children
    self_model = parent[:model_name].camelcase(:upper).constantize
    kids = self_model.children_models
    unless kids.nil? || kids.empty?
      kids.each do |k|
        # check if the kids have a json object at this level
        if h[k[:xml_name]]
          logger.debug "XML child is #{k[:xml_name]}"
          logger.debug "Model name is #{k[:model_name]}"
          if h[k[:xml_name]].is_a? Array
            logger.debug "#{k[:xml_name]} is an array, will add all the objects"
            h[k[:xml_name]].each do |h_instance|
              klass = k[:model_name].camelcase(:upper).constantize
              if klass.respond_to? :from_sdd_json
                model = klass.from_sdd_json(k, h_instance)

                # Assign the foreign key on the object
                model["#{parent[:model_name]}_id"] = self.id
                model.save!
              else
                logger.warn "Class #{klass} does not have instance method 'from_sdd_json'"
              end
            end
          elsif h[k[:xml_name]].is_a? Hash
            logger.debug "#{k[:xml_name]} is a single object, will add only one"
            klass = k[:model_name].camelcase(:upper).constantize
            if klass.respond_to? :from_sdd_json
              model = klass.from_sdd_json(k, h[k[:xml_name]])

              # Assign the foreign key on the object
              model["#{parent[:model_name]}_id"] = self.id
              model.save!
            else
              logger.warn "Class #{klass} does not have instance method 'from_sdd_json'"
            end
          end
        end
      end
    end
  end

  
  def status_enums
    [
      'New',
      'Existing'
    ]
  end

  def type_enums
    [
      'OpenTower',
      'ClosedTower',
      'GroundSourceHeatExchanger',
      'Lake',
      'Well'
    ]
  end

  def fan_type_enums
    [
      'Axial',
      'Centrifugal'
    ]
  end

  def modulation_control_enums
    [
      'Bypass',
      'Cycling',
      'TwoSpeed',
      'VariableSpeedDrive'
    ]
  end
end