class TerminalUnit
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String
  field :status, type: String
  field :type, type: String
  field :zone_served_reference, type: String
  field :count, type: Integer
  field :minimum_air_fraction_schedule_reference, type: String
  field :primary_air_segment_reference, type: String
  field :primary_air_flow_maximum, type: Float
  field :primary_air_flow_minimum, type: Float
  field :heating_air_flow_maximum, type: Float
  field :reheat_control_method, type: String
  field :induced_air_zone_reference, type: String
  field :induction_ratio, type: Float
  field :fan_power_per_flow, type: Float
  field :parallel_box_fan_flow_fraction, type: Float

  belongs_to :air_system
  has_many :coil_heatings, dependent: :destroy
  has_many :fans, dependent: :destroy


  def self.children_models
    children = [
       { model_name: 'coil_heating', xml_name: 'CoilHtg' },
       { model_name: 'fan', xml_name: 'Fan' }
    ]
  end

  def self.xml_fields
    xml_fields = [
      {:db_field_name=>"name", :xml_field_name=>"Name"},
      {:db_field_name=>"status", :xml_field_name=>"Status"},
      {:db_field_name=>"type", :xml_field_name=>"Type"},
      {:db_field_name=>"zone_served_reference", :xml_field_name=>"ZnServedRef"},
      {:db_field_name=>"count", :xml_field_name=>"Cnt"},
      {:db_field_name=>"minimum_air_fraction_schedule_reference", :xml_field_name=>"MinAirFracSchRef"},
      {:db_field_name=>"primary_air_segment_reference", :xml_field_name=>"PriAirSegRef"},
      {:db_field_name=>"primary_air_flow_maximum", :xml_field_name=>"PriAirFlowMax"},
      {:db_field_name=>"primary_air_flow_minimum", :xml_field_name=>"PriAirFlowMin"},
      {:db_field_name=>"heating_air_flow_maximum", :xml_field_name=>"HtgAirFlowMax"},
      {:db_field_name=>"reheat_control_method", :xml_field_name=>"ReheatCtrlMthd"},
      {:db_field_name=>"induced_air_zone_reference", :xml_field_name=>"InducedAirZnRef"},
      {:db_field_name=>"induction_ratio", :xml_field_name=>"InductionRat"},
      {:db_field_name=>"fan_power_per_flow", :xml_field_name=>"FanPwrPerFlow"},
      {:db_field_name=>"parallel_box_fan_flow_fraction", :xml_field_name=>"ParallelBoxFanFlowFrac"}
    ]
  end


  # This method is autogenerated. Do not change directly.
  def to_sdd_xml(meta, xml)
    xml.send(meta[:xml_name]) do
      self.class.xml_fields.each do |field|
        if self[field[:db_field_name]]
          if self[field[:db_field_name]].is_a? Array
            logger.debug "Translating to XML and the object is an Array"
            self[field[:db_field_name]].each_with_index do |instance, index|
              xml.send(:"#{field[:xml_field_name]}", instance, "index" => index)
            end
          else
            xml.send(:"#{field[:xml_field_name]}", self[field[:db_field_name]])
          end
        end
      end

      # go through children if they have something to add, call their methods
      kids = self.class.children_models
      unless kids.nil? || kids.empty?
        kids.each do |k|
          models = self.send(k[:model_name].pluralize)
          models.each do |m|
            m.to_sdd_xml(k, xml)
          end
        end
      end
    end
  end
      
  # This method is autogenerated. Do not change directly.
  # Take the map of model name and xml name, and the hash (from the XML).
  def self.from_sdd_json(meta, h)
    o = nil
    if meta && h
      self_model = meta[:model_name].camelcase(:upper).constantize
      o = self_model.create_from_sdd_json(meta, h)
      if o
        o.create_children_from_sdd_json(meta, h)
        o.save!
        o.reload # in case of relationships being updated
      else
        fail "Could not create instance of #{self_model} for #{meta[:model_name]}"
      end
    end

    o
  end
  
  # This method is autogenerated. Do not change directly.
  def self.create_from_sdd_json(meta, h)
    new_h = {}

    # Find fields as defined by the XML
    self_model = meta[:model_name].camelcase(:upper).constantize
    self_model.xml_fields.each do |field|
      if h[field[:xml_field_name]]
        logger.debug "Field Data Type: #{self_model.fields[field[:db_field_name]].options[:type]}"
        if self_model.fields[field[:db_field_name]].options[:type].to_s == 'Array'
          logger.debug "Data model has an array as the field"
          # check if the hash has an array, otherwise make it an array
          if h[field[:xml_field_name]].is_a? Array
            logger.debug "XML/JSON field is already an Array"
            new_h[field[:db_field_name]] = h[field[:xml_field_name]]
          else
            new_h[field[:db_field_name]] = [h[field[:xml_field_name]]]
          end
        else
          new_h[field[:db_field_name]] = h[field[:xml_field_name]]
        end
      end
    end

    # new_h can be empty if the xml has no fields, but still create the object
    o = self_model.new(new_h)

    o
  end

  # This method is autogenerated. Do not change directly.
  def create_children_from_sdd_json(meta, h)
    # Go through the children
    self_model = meta[:model_name].camelcase(:upper).constantize
    kids = self_model.children_models
    unless kids.nil? || kids.empty?
      kids.each do |k|
        # check if the kids have a json object at this level
        if h[k[:xml_name]]
          logger.debug "XML child is #{k[:xml_name]}"
          logger.debug "Model name is #{k[:model_name]}"
          if h[k[:xml_name]].is_a? Array
            logger.debug "#{k[:xml_name]} is an array, will add all the objects"
            h[k[:xml_name]].each do |h_instance|
              klass = k[:model_name].camelcase(:upper).constantize
              if klass.respond_to? :from_sdd_json
                model = klass.from_sdd_json(k, h_instance)

                # Assign the foreign key on the object
                model["#{meta[:model_name]}_id"] = self.id
                model.save!
              else
                logger.warn "Class #{klass} does not have instance method 'from_sdd_json'"
              end
            end
          elsif h[k[:xml_name]].is_a? Hash
            logger.debug "#{k[:xml_name]} is a single object, will add only one"
            klass = k[:model_name].camelcase(:upper).constantize
            if klass.respond_to? :from_sdd_json
              model = klass.from_sdd_json(k, h[k[:xml_name]])

              # Assign the foreign key on the object
              model["#{meta[:model_name]}_id"] = self.id
              model.save!
            else
              logger.warn "Class #{klass} does not have instance method 'from_sdd_json'"
            end
          end
        end
      end
    end
  end
  
  def status_enums
    [
      'New',
      'Existing'
    ]
  end

  def type_enums
    [
      '- specify -',
      'Uncontrolled',
      'VAVReheatBox',
      'ParallelFanBox',
      'SeriesFanBox',
      'VAVNoReheatBox'
    ]
  end

  def reheat_control_method_enums
    [
      'SingleMaximum',
      'DualMaximum'
    ]
  end
end