class ZoneSystem
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String
  field :status, type: String
  field :type, type: String
  field :description, type: String
  field :hvac_auto_sizing, type: Integer
  field :fan_control, type: String
  field :cooling_control, type: String
  field :count, type: Integer
  field :cooling_design_supply_air_temperature, type: Float
  field :heating_design_supply_air_temperature, type: Float
  field :exhaust_system_type, type: String
  field :exhaust_operation_mode, type: String
  field :exhaust_control_method, type: String
  field :air_distribution_type, type: String

  belongs_to :building
  has_many :coil_coolings, dependent: :destroy
  has_many :coil_heatings, dependent: :destroy
  has_many :fans, dependent: :destroy


  def self.children_models
    children = [
       { model_name: 'coil_cooling', xml_name: 'CoilClg' },
       { model_name: 'coil_heating', xml_name: 'CoilHtg' },
       { model_name: 'fan', xml_name: 'Fan' }
    ]
  end

  def self.xml_fields
    xml_fields = [
      {:db_field_name=>"name", :xml_field_name=>"Name"},
      {:db_field_name=>"status", :xml_field_name=>"Status"},
      {:db_field_name=>"type", :xml_field_name=>"Type"},
      {:db_field_name=>"description", :xml_field_name=>"Desc"},
      {:db_field_name=>"hvac_auto_sizing", :xml_field_name=>"HVACAutoSizing"},
      {:db_field_name=>"fan_control", :xml_field_name=>"FanCtrl"},
      {:db_field_name=>"cooling_control", :xml_field_name=>"ClgCtrl"},
      {:db_field_name=>"count", :xml_field_name=>"Cnt"},
      {:db_field_name=>"cooling_design_supply_air_temperature", :xml_field_name=>"ClgDsgnSupAirTemp"},
      {:db_field_name=>"heating_design_supply_air_temperature", :xml_field_name=>"HtgDsgnSupAirTemp"},
      {:db_field_name=>"exhaust_system_type", :xml_field_name=>"ExhSysType"},
      {:db_field_name=>"exhaust_operation_mode", :xml_field_name=>"ExhOperMode"},
      {:db_field_name=>"exhaust_control_method", :xml_field_name=>"ExhCtrlMthd"},
      {:db_field_name=>"air_distribution_type", :xml_field_name=>"AirDistType"}
    ]
  end


  # This method is autogenerated. Do not change directly.
  def to_sdd_xml(meta, xml)
    xml.send(meta[:xml_name]) do
      self.class.xml_fields.each do |field|
        if self[field[:db_field_name]]
          if self[field[:db_field_name]].is_a? Array
            logger.debug "Translating to XML and the object is an Array"
            self[field[:db_field_name]].each_with_index do |instance, index|
              xml.send(:"#{field[:xml_field_name]}", instance, "index" => index)
            end
          else
            xml.send(:"#{field[:xml_field_name]}", self[field[:db_field_name]])
          end
        end
      end

      # go through children if they have something to add, call their methods
      kids = self.class.children_models
      unless kids.nil? || kids.empty?
        kids.each do |k|
          models = self.send(k[:model_name].pluralize)
          models.each do |m|
            m.to_sdd_xml(k, xml)
          end
        end
      end
    end
  end
      
  # This method is autogenerated. Do not change directly.
  # Take the map of model name and xml name, and the hash (from the XML).
  def self.from_sdd_json(meta, h)
    o = nil
    if meta && h
      self_model = meta[:model_name].camelcase(:upper).constantize
      o = self_model.create_from_sdd_json(meta, h)
      if o
        o.create_children_from_sdd_json(meta, h)
        o.save!
        o.reload # in case of relationships being updated
      else
        fail "Could not create instance of #{self_model} for #{meta[:model_name]}"
      end
    end

    o
  end
  
  # This method is autogenerated. Do not change directly.
  def self.create_from_sdd_json(meta, h)
    new_h = {}

    # Find fields as defined by the XML
    self_model = meta[:model_name].camelcase(:upper).constantize
    self_model.xml_fields.each do |field|
      if h[field[:xml_field_name]]
        logger.debug "Field Data Type: #{self_model.fields[field[:db_field_name]].options[:type]}"
        if self_model.fields[field[:db_field_name]].options[:type].to_s == 'Array'
          logger.debug "Data model has an array as the field"
          # check if the hash has an array, otherwise make it an array
          if h[field[:xml_field_name]].is_a? Array
            logger.debug "XML/JSON field is already an Array"
            new_h[field[:db_field_name]] = h[field[:xml_field_name]]
          else
            new_h[field[:db_field_name]] = [h[field[:xml_field_name]]]
          end
        else
          new_h[field[:db_field_name]] = h[field[:xml_field_name]]
        end

      end
    end

    # new_h can be empty if the xml has no fields, but still create the object
    o = self_model.new(new_h)

    o
  end

  # This method is autogenerated. Do not change directly.
  def create_children_from_sdd_json(meta, h)
    # Go through the children
    self_model = meta[:model_name].camelcase(:upper).constantize
    kids = self_model.children_models
    unless kids.nil? || kids.empty?
      kids.each do |k|
        # check if the kids have a json object at this level
        if h[k[:xml_name]]
          logger.debug "XML child is #{k[:xml_name]}"
          logger.debug "Model name is #{k[:model_name]}"
          if h[k[:xml_name]].is_a? Array
            logger.debug "#{k[:xml_name]} is an array, will add all the objects"
            h[k[:xml_name]].each do |h_instance|
              klass = k[:model_name].camelcase(:upper).constantize
              if klass.respond_to? :from_sdd_json
                model = klass.from_sdd_json(k, h_instance)

                # Assign the foreign key on the object
                model["#{meta[:model_name]}_id"] = self.id
                model.save!
              else
                logger.warn "Class #{klass} does not have instance method 'from_sdd_json'"
              end
            end
          elsif h[k[:xml_name]].is_a? Hash
            logger.debug "#{k[:xml_name]} is a single object, will add only one"
            klass = k[:model_name].camelcase(:upper).constantize
            if klass.respond_to? :from_sdd_json
              model = klass.from_sdd_json(k, h[k[:xml_name]])

              # Assign the foreign key on the object
              model["#{meta[:model_name]}_id"] = self.id
              model.save!
            else
              logger.warn "Class #{klass} does not have instance method 'from_sdd_json'"
            end
          end
        end
      end
    end
  end

  
  def status_enums
    [
      'New',
      'Existing',
      'Altered'
    ]
  end

  def type_enums
    [
      '- specify -',
      'PTAC',
      'PTHP',
      'FPFC',
      'Baseboard',
      'WSHP',
      'Exhaust'
    ]
  end

  def fan_control_enums
    [
      'Continuous',
      'Cycling'
    ]
  end

  def cooling_control_enums
    [
      'NoSATControl'
    ]
  end

  def exhaust_system_type_enums
    [
      'General',
      'Laboratory',
      'CommercialKitchen',
      'ParkingGarage'
    ]
  end

  def exhaust_operation_mode_enums
    [
      'DecoupledFromSystem',
      'CoupledToSystem'
    ]
  end

  def exhaust_control_method_enums
    [
      'ConstantFlowConstantSpeedFan',
      'VariableFlowConstantSpeedFan',
      'VariableFlowVariableSpeedFan',
      'NoCOControl',
      'COControl'
    ]
  end

  def air_distribution_type_enums
    [
      'Mixing',
      'None'
    ]
  end
end